version: '3.8'
services:
    encode-worker:
        env_file:
        - .env
        # remove the privileged option if it causes error
        privileged: true
        restart:
            always
        deploy:
            resources:
              reservations:
                devices:
                - driver: nvidia
                  count: all
                  capabilities: [gpu]
        build:
            context: .
        volumes:
            - ./:/code/app
            - ./v2:/code/app/v2
