version: '3.8'
services:
    encode-worker:
        env_file:
        - .env
        privileged: true
        restart:
            unless-stopped
        deploy:
            resources:
              reservations:
                devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]
        build:
            dockerfile: Dockerfile.prod
            context: .
        volumes:
            - ./:/code/app
            - ./v2:/code/app/v2
