version: '3'
services:
    encode-worker:
        env_file:
        - .env
        build:
            context: .
        volumes:
            - ./:/code/app
            - ./v2:/code/app/v2
        environment:
            - CUDA_VISIBLE_DEVICES=1
        ipc: "host"